language: node_js

node_js:
- '15'

os:
- linux
dist: focal # using Ubuntu 20.04 LTS

branches:
  only:
  - master

env:
  global:
    - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$

before_install:
- npm install -g vsce

script:
- vsce package

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Guillaume Barré"
  - git config --local user.email "guillaume.barre@ac-versailles.fr"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  # deploy to github release
  - provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
