env:
  - PACKAGE_VERSION="0.0.2"

language: node_js

node_js:
- '15'

os:
- linux
dist: focal # using Ubuntu 20.04 LTS

branches:
  only:
  - master

before_install:
- npm install -g vsce

script:
- vsce package

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Guillaume Barre"
  - git config --local user.email "guillaume.barre@ac-versailles.fr"
  - git tag v${PACKAGE_VERSION}

deploy:
  # deploy to github release
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "dsi-versailles-system-${PACKAGE_VERSION}.vsix"
    skip_cleanup: true
