language: node_js

node_js:
- '15'

os:
- linux
dist: focal # using Ubuntu 20.04 LTS

branches:
  only:
  - master

env:
  global:
    - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$

before_install:
- npm install -g vsce

script:
- vsce package

deploy:
  # deploy to github release
  - provider: releases
    api_key: $GIT_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_OS_NAME == linux"