language: node_js

node_js:
- '15'

os:
- linux
dist: focal # using Ubuntu 20.04 LTS

branches:
  only:
  - master

before_install:
- npm install -g vsce

script:
- vsce package

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Guillaume Barre"
  - git config --local user.email "guillaume.barre@ac-versailles.fr"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - ls -la && ls -la ..

deploy:
  # deploy to github release
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "dsi-versailles-system-0.0.1.vsix"
    skip_cleanup: true
